### ISSUE TITLE
Which revision are these tutorial based on?

### ISSUE THREAD

**Issue by nextfool** [danbev/learning-nodejs#5]
Hi,
First of all thank you so much for such great learning resources. 
Since the node source code changes rapidly, could you please tell me the git revision/tag/branch or node version number which these articles are based on? So that I can learn more efficiently as a beginner? 

Thank you.

**Comment by danbev** [comment]
> Since the node source code changes rapidly, could you please tell me the git revision/tag/branch or node version number which these articles are based on?

I was only using the latest version at the time (latest master/main) branch. Some of the notes are out of date and the idea was to update them from time to time when revisiting a certain area.

**Comment by nextfool** [comment]
Hi @danbev,
Thank you for the kind explanation.
I am now closing the issue.
